/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CustomButton: typeof import('./src/components/ui/CustomButton.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HomeActionsComponent: typeof import('./src/components/HomeActionsComponent.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    MarkLoaderComponent: typeof import('./src/components/MarkLoaderComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkoutsOfTheDayComponent: typeof import('./src/components/WorkoutsOfTheDayComponent.vue')['default']
  }
}
