/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CustomButton: typeof import('./src/components/ui/CustomButton.vue')['default']
    FooterComponent: typeof import('./src/components/footerComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/headerComponent.vue')['default']
    MarkLoaderComponent: typeof import('./src/components/markLoaderComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
